### ISSUE TITLE
function name in base color in Clojure

### ISSUE THREAD

**Issue by narocath** [sjl/badwolf#34]
The function name after defn also after def.. is white. How can I change it?

**Comment by sjl** [comment]
Find out what your syntax file tags the name as, then add it with your desired color here:

https://github.com/sjl/badwolf/blob/master/colors/badwolf.vim#L433

Unfortunately it looks like the Clojure syntax file just tags this as `clojureSymbol` like all other normal symbols, so changing it would also change every other symbol.  If you want to highlight the function names differently you'll need to edit the syntax file to recognize them first.
